### ISSUE TITLE
Query Block crashes kicli

### ISSUE THREAD

**Issue by unordered-set** [KiFoundation/ki-networks#916]
```
$ kicli --home ki-node/kicli query block 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc8d495]

goroutine 1 [running]:
github.com/tendermint/tendermint/lite/proxy.GetCertifiedCommit(0x2, 0x1342620, 0xc000f0c930, 0x0, 0x0, 0x5, 0xc000f0c960, 0xe26820, 0xc000eed690)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.10/lite/proxy/query.go:140 +0x105
github.com/cosmos/cosmos-sdk/client/context.CLIContext.Verify(0x0, 0x1342620, 0xc000f0c930, 0x0, 0x0, 0x130e4c0, 0xc000100008, 0xfe4bb9, 0x4, 0x0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.9/client/context/query.go:116 +0x66
github.com/cosmos/cosmos-sdk/client/rpc.getBlock(0x0, 0x1342620, 0xc000f0c930, 0x0, 0x0, 0x130e4c0, 0xc000100008, 0xfe4bb9, 0x4, 0x0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.9/client/rpc/block.go:51 +0x202
github.com/cosmos/cosmos-sdk/client/rpc.printBlock(0xc000177900, 0xc000f0c270, 0x1, 0x3, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.9/client/rpc/block.go:106 +0xa3
github.com/spf13/cobra.(*Command).execute(0xc000177900, 0xc000ed6c40, 0x3, 0x4, 0xc000177900, 0xc000ed6c40)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000176000, 0x88a1d0, 0xc000176000, 0xfe3bc4)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000176000, 0x11dc690, 0x2, 0xc000e68c50)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.10/libs/cli/setup.go:89 +0x3c
main.main()
        /root/ki/cmd/kicli/main.go:115 +0x59d

$ kicli version --long
name: ki-tools
server_name: kid
client_name: kicli
version: 0.1-13-g711e19e-Testnet
commit: 711e19ebbb516ae6d38c638634c4bef05201be72
build_tags: netgo,ledger
go: go version go1.13.5 linux/amd64
```

**Comment by unordered-set** [comment]
Hm, adding `--trust-node` helped
